# [Task]: T063 | [Spec]: specs/005-phase-05-cloud-native/spec.md
# Dapr declarative subscription for task events (backup - programmatic preferred)
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: task-events-subscription
spec:
  pubsubname: task-pubsub
  topic: task-events
  routes:
    default: /events/task-events
scopes:
  - audit-service
